#!/bin/bash
# select-default-audio.sh — choose the ALSA default output at boot.
#
# Prefer the USB sound card (named "WaveshareUSB" by 90-waveshare-usb-audio.rules
# regardless of port). If it isn't present — not installed, or it failed to
# enumerate (which the JMTek 0c76:1203 dongle does at boot when the display is
# powered through the Pi's USB) — fall back to the connected HDMI display's
# speakers. Net effect: the build always has working audio, dongle or not.
#
# Run once at boot by select-default-audio.service, before EmulationStation.
set -u

ASOUND=/etc/asound.conf
USB_NAME="WaveshareUSB"
log(){ logger -t select-default-audio "$*"; echo "$*"; }

# --- USB sound card present? -> make it the default (dmix so apps can share) ---
if aplay -l 2>/dev/null | grep -qi "$USB_NAME"; then
    cat > "$ASOUND" <<EOF
# Auto-generated by select-default-audio.service: USB sound card present.
pcm.!default {
    type plug
    slave.pcm "dmix_waveshare"
}
pcm.dmix_waveshare {
    type dmix
    ipc_key 2048
    ipc_key_add_uid yes
    slave { pcm "hw:$USB_NAME,0"; rate 48000; channels 2 }
}
ctl.!default { type hw; card $USB_NAME }
EOF
    log "USB sound card ($USB_NAME) present -> default audio = USB"
    exit 0
fi

# --- No USB card -> pick the connected HDMI output's ALSA card ---
# Best-effort map: drm HDMI-A-1 -> vc4hdmi0, HDMI-A-2 -> vc4hdmi1.
HDMI_CARD="vc4hdmi0"
for s in /sys/class/drm/card*-HDMI-A-*/status; do
    [ "$(cat "$s" 2>/dev/null)" = "connected" ] || continue
    case "$s" in
        *HDMI-A-1*) HDMI_CARD="vc4hdmi0" ;;
        *HDMI-A-2*) HDMI_CARD="vc4hdmi1" ;;
    esac
    break
done

cat > "$ASOUND" <<EOF
# Auto-generated by select-default-audio.service: no USB sound card; using HDMI.
pcm.!default { type plug; slave.pcm "hw:$HDMI_CARD,0" }
ctl.!default { type hw; card $HDMI_CARD }
EOF
log "No USB sound card -> default audio = HDMI ($HDMI_CARD)"
